version: '3'
services:
  namenode:
    container_name: namenode
    image: hadoop-namenode:0.0.2
    networks:
      net:
        ipv4_address: 172.18.0.10
    ports:
            - "50070:50070"
        
  datanode01:
    image: hadoop-yarn:0.0.2
    container_name: datanode01
    networks:
      net:
        ipv4_address: 172.18.0.11
    ports:
            - "8088:8088"
        
  datanode03:
    image: hadoop-datanode:0.0.2
    container_name: datanode02
    networks:
      net:
        ipv4_address: 172.18.0.12

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
